let api = {
  songs: [
    {
      title: "All I Want",
      author: "Kodaline",
      url: "./media/all-i-want.mp3",
      photoUrl: "./img/all-i-want-cover.jpg",
      duration: "5:05",
      lrcUrl: "./media/all-i-want.lrc",
    },
    {
      title: "Complicated",
      author: "Olivia O'Brien",
      url: "./media/complicated.mp3",
      photoUrl: "./img/complicated-cover.jpg",
      duration: "3:09",
      lrcUrl: "./media/complicated.lrc",
    },
    {
      title: "It's You",
      author: "Ali Gatie",
      url: "./media/its-you.mp3",
      photoUrl: "./img/its-you-cover.jpg",
      duration: "3:32",
      lrcUrl: "./media/its-you.lrc",
    },
    {
      title: "This Love",
      author: "Davichi",
      url: "./media/this-love.mp3",
      photoUrl: "./img/this-love-cover.jpg",
      duration: "3:45",
      lrcUrl: "./media/this-love.lrc",
    },
    {
      title: "What am I",
      author: "Why don't We",
      url: "./media/what-am-i.mp3",
      photoUrl: "./img/what-am-i-cover.jpg",
      duration: "3:04",
      lrcUrl: "./media/what-am-i.lrc",
    },
    {
      title: "More than Friends",
      author: "Jason Mraz",
      url: "./media/more-than-friends.mp3",
      photoUrl: "./img/more-than-friends-cover.jpg",
      duration: "3:01",
      lrcUrl: "./media/more-than-friends.lrc",
    },
    {
      title: "Wake me up",
      author: "Avicii",
      url: "./media/wake-me-up.mp3",
      photoUrl: "./img/wake-me-up-cover.jpg",
      duration: "4:07",
      lrcUrl: "./media/wake-me-up.lrc",
    },
  ],
};
